language: php

before_script:
  - if ! git show-ref --quiet master; then
      git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/* ;
      git fetch --tags ;
      git branch master origin/master ;
    fi
  - composer install

# see https://github.com/travis-ci/travis-ci/issues/4942#issuecomment-159132444
git:
  depth: 99999

deploy:
  provider: releases
  api_key:
    secure: "lK49QbYeVNiXSdZbnO2q3vtCIRYaB7E4SAeVOjOAS28vMo57sw678Hyg70BSmhHyr079B3RyExduV7WKAi0IY2d+YfGja3lptr+ana1rNEmBvjT/I7x1BIzukvuGa8PWpFN+gNvQhgA3bKVDtWsQhhDPdiC6JwJSlGDW8wfI+VxTQ6x109WM0QbzQzHE2D7QRQoRQ89V56U4vL3lJ17fu0LUXsHwD+fExvL5COEUzrT5J4oGGS8gIxSZtst29ecrpHXuXm3M8YrmWQGcLVUFi1Hgf2VH4DwJdm6xx3CG4c8iuSYBVLvCZeYSr6GbAGlFD5ailolLvklgkkWvLD9RNeLBXMupaUHdhOmjFaeMQ0SL+hqCJ8rJljouN7KMTvgmpsiearLmmWNV7pHrrbEtYGvEB+fDByW8ETX4w9sK2MJhBPMRPVCMq6afVjiNk+g9nOjHQ3bECyXsE0CgKhULrg9lB0MTcwI/lbTxMMOk2qYWdVulPUODk5spVEU98ZZSIWxYu5SZP5YW/s62xy1PJuKU17X60K89t6DX5ctwe5sbedTwH/8l0JP2tx52Hfdye2o/1Dw7pB8y6wgO3FT7XQ/v8+44qaM8kwuYLixo8Z9/yilCL1D6XnfXOQl8ZSrUmj7tNSAuCOGa1/uxt2bC3jheTGhD2Ch7557Cy1+P6l4="
  file: dist/roave-backward-compatibility-check.phar
  skip_cleanup: true
  on:
    tags: true

jobs:
  include:

    - stage: Static Analysis (src) with Psalm
      php: 7.2
      script: vendor/bin/psalm

    #- stage: Static analysis (src) with phpstan
    #  php: 7.2
    #  script: vendor/bin/phpstan analyse --level=7 src

    - stage: Test
      php: 7.2
      script: vendor/bin/phpunit

    - stage: Code Coverage
      php: 7.2
      before_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - composer install
      script:
        - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml

    - stage: Coding Standards
      php: 7.2
      script: vendor/bin/phpcs

    #- stage: Mutation Tests
    #  php: 7.2
    #  script: vendor/bin/infection

    - stage: Verify BC Breaks
      php: 7.2
      script: bin/roave-backward-compatibility-check --from=master --to=HEAD

    - stage: Build release PHAR
      php: 7.2
      script: ./build-phar.sh
      if: tag IS present

cache:
  directories:
    - $HOME/.composer/cache
